-- =============================================================
-- Migrate legacy auto-generated English nicknames to Korean-base nicknames
-- =============================================================
-- Target rows:
--   - profiles.nickname shaped as "<old_adjective>_<old_noun>"
--   - token pairs generated by the legacy nickname generator
--
-- Safety:
--   - rows not matching legacy generator tokens are untouched
--   - unique collisions against existing nicknames are resolved by appending
--     a short user-id suffix (e.g., "_a1b2c3")
-- =============================================================

WITH adjective_map(old_adj, new_adj) AS (
  VALUES
    ('brave', '고요한'),
    ('calm', '따뜻한'),
    ('dark', '은은한'),
    ('early', '반짝이는'),
    ('fast', '포근한'),
    ('gentle', '맑은'),
    ('happy', '산뜻한'),
    ('idle', '부드러운'),
    ('jolly', '단단한'),
    ('kind', '차분한'),
    ('lazy', '선명한'),
    ('mild', '담대한'),
    ('neat', '느긋한'),
    ('odd', '활기찬'),
    ('proud', '싱그러운'),
    ('quiet', '느린'),
    ('rare', '빠른'),
    ('soft', '넓은'),
    ('tiny', '깊은'),
    ('vast', '짙은'),
    ('warm', '희미한'),
    ('wild', '반가운'),
    ('wise', '수줍은'),
    ('young', '당찬'),
    ('zesty', '명랑한'),
    ('amber', '청량한'),
    ('azure', '순한'),
    ('bold', '빛나는'),
    ('crisp', '청명한'),
    ('dusk', '새벽의'),
    ('faint', '노을빛'),
    ('golden', '별빛'),
    ('hazy', '은빛'),
    ('ivory', '바람결'),
    ('jade', '달콤한'),
    ('lush', '상쾌한'),
    ('mossy', '평온한'),
    ('noble', '다정한'),
    ('opal', '기민한'),
    ('pale', '영롱한'),
    ('rusty', '맑아진'),
    ('sandy', '유연한'),
    ('swift', '튼튼한'),
    ('teal', '온화한'),
    ('urban', '깜찍한')
),
noun_map(old_noun, new_noun) AS (
  VALUES
    ('bear', '고양이'),
    ('bird', '여우'),
    ('cloud', '늑대'),
    ('dawn', '바다'),
    ('echo', '강'),
    ('field', '호수'),
    ('fox', '구름'),
    ('grove', '별'),
    ('hill', '달'),
    ('isle', '바람'),
    ('lake', '숲'),
    ('leaf', '나무'),
    ('moon', '돌'),
    ('moth', '모래'),
    ('mist', '파도'),
    ('oak', '노을'),
    ('path', '새벽'),
    ('pine', '안개'),
    ('rain', '비'),
    ('reef', '눈'),
    ('river', '산'),
    ('rock', '들판'),
    ('rose', '해변'),
    ('sage', '골목'),
    ('sand', '등대'),
    ('sea', '섬'),
    ('snow', '언덕'),
    ('star', '꽃'),
    ('stone', '장미'),
    ('storm', '잎새'),
    ('tide', '새'),
    ('tree', '곰'),
    ('vale', '토끼'),
    ('wave', '사슴'),
    ('wind', '고래'),
    ('wolf', '나비'),
    ('wood', '갈대'),
    ('brook', '시냇물'),
    ('cliff', '절벽'),
    ('cove', '동굴'),
    ('creek', '파랑새'),
    ('dune', '유성'),
    ('fern', '은하'),
    ('ford', '물안개'),
    ('glade', '바위')
),
mapped AS (
  SELECT
    p.id,
    p.nickname AS old_nickname,
    (am.new_adj || '_' || nm.new_noun) AS base_nickname
  FROM profiles p
  JOIN adjective_map am
    ON am.old_adj = split_part(p.nickname, '_', 1)
  JOIN noun_map nm
    ON nm.old_noun = split_part(p.nickname, '_', 2)
  WHERE split_part(p.nickname, '_', 3) = ''
),
resolved AS (
  SELECT
    m.id,
    m.old_nickname,
    CASE
      WHEN EXISTS (
        SELECT 1
        FROM profiles p2
        WHERE p2.id <> m.id
          AND p2.nickname = m.base_nickname
      )
      THEN m.base_nickname || '_' || substr(replace(m.id::text, '-', ''), 1, 6)
      ELSE m.base_nickname
    END AS new_nickname
  FROM mapped m
)
UPDATE profiles p
SET nickname = r.new_nickname
FROM resolved r
WHERE p.id = r.id
  AND p.nickname <> r.new_nickname;

